spring.application.name=task-manager

spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanagerdb
spring.datasource.username=taskmanageruser
spring.datasource.password=taskmanagerpassword

spring.jpa.hibernate.ddl-auto=update